site_name: From Docker to Kubernetes - Multi-Arch with Go and Nodejs
repo_url: https://github.com/siler23/MultiArchDockerICP
edit_uri: ''
nav:
    - Home: index.md
    - 0. Hello Proxy Users: 0-ProxyPSA.md
    - 1. Getting Official with Multi-arch Images: 1-Official-Multiarch.md
    - 2. Learning How to Build Best-practice Node.js Docker Images: 2-Best-Practice-Nodejs.md
    - 3. Guide to Building Best-practice Go Docker Images: 3-Best-Practice-go.md
    - 4. Building Multi-arch Docker Images:
        - Bringing Multi-arch Images to a Computer Near You: 4-Build-MultiArch.md
        - The future - Using Buildx to make Multi-arch a Way of Life: 4-Multiarch-buildx-addendum.md
        - The past - The Manual Way aka Herding Cats: 4-Multiarch-manual-addendum.md
    - 5. Kubernetes Time: 5-Deploy-to-Kubernetes.md

theme: material
markdown_extensions:
  - admonition
