apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: small-outyet
    lab: multi-arch-docker
  name: multi-arch-docker-small-outyet
spec:
  selector:
    matchLabels:
      app: small-outyet
      lab: multi-arch-docker
  replicas: 1
  template:
    metadata: {labels: {app: small-outyet, lab: multi-arch-docker}}
    spec:
      containers:
      - name: small-outyet
        image: gmoney23/small-outyet:1.0
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: multi-arch-docker-proxy-config
            optional: true
      tolerations: 
      - key: "arch"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"
