apiVersion: v1
kind: Service
metadata: 
  name: multi-arch-docker-small-outyet
  labels:
    app: small-outyet
    lab: multi-arch-docker
spec:
  selector:
    app: small-outyet
    lab: multi-arch-docker
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
