apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: 
    app: go-example
  name: go-example
spec:
  selector:
    matchLabels:
      app: go-example
  replicas: 1
  template:
    metadata: {labels: {app: go-example}}
    spec:
      containers:
      - name: go-example
        image: gmoney23/example-go-server:1.0
        ports:
          - containerPort: 5000
