apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: go-example
  name: go-example
  selfLink: /api/v1/namespaces/blockchain-dev/services/go-example
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: go-example
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
