apiVersion: v1
kind: Service
metadata: 
  name: multi-arch-docker-go-example
  labels: 
    app: go-example
    lab: multi-arch-docker
spec:
  selector:
    app: go-example
    lab: multi-arch-docker
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
