apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: {app: outyet, lab: multi-arch-docker}
  name: multi-arch-docker-outyet
spec:
  selector:
    matchLabels:
      app: outyet
      lab: multi-arch-docker
  replicas: 1
  template:
    metadata: {labels: {app: outyet, lab: multi-arch-docker}}
    spec:
      containers:
      - name: outyet
        image: gmoney23/outyet:1.0
        ports:
          - containerPort: 8080
        envFrom:
        - configMapRef:
            name: multi-arch-docker-proxy-config
            optional: true
