apiVersion: v1
kind: Service
metadata: 
  name: multi-arch-docker-outyet 
  labels:
    app: outyet
    lab: multi-arch-docker    
spec:
  selector:
    app: outyet
    lab: multi-arch-docker
  ports:
  - protocol: TCP
    port: 8080
  type: NodePort
