apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: 
    app: node-web
    lab: multi-arch-docker
  name: multi-arch-docker-node-web
spec:
  selector:
    matchLabels:
      app: node-web
      lab: multi-arch-docker
  replicas: 1
  template:
    metadata: {labels: {app: node-web, lab: multi-arch-docker}}
    spec:
      containers:
      - name: node-web
        image: gmoney23/node-web-app:1.0
        ports:
          - containerPort: 8080
