apiVersion: v1
kind: Service
metadata: 
  name: multi-arch-docker-node-web
  labels: 
    app: node-web
    lab: multi-arch-docker
spec:
  selector:
    app: node-web
    lab: multi-arch-docker
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
