apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels: 
    app: smallest-outyet
  name: smallest-outyet
spec:
  selector:
    matchLabels:
      app: smallest-outyet
  replicas: 1
  template:
    metadata: {labels: {app: smallest-outyet}}
    spec:
      containers:
      - name: smallest-outyet
        image: gmoney23/smallest-outyet:1.0
        ports:
          - containerPort: 8080
