version : 0.0.3

container-name-run : "nodejs-sample"
container-name-tools : "nodejs-sample"

host-path-run : .
host-path-tools : .

container-path-run : "/app"
container-path-tools : "/app"

container-port-map : "3000:3000"
container-port-map-debug : "5858:5858"

dockerfile-run : "Dockerfile"

image-name-run : "nodejs-sample"
image-name-tools : "nodejs-sample"

build-cmd-run : "npm install"
test-cmd : "npm run test"
build-cmd-debug : "npm install"

run-cmd : ""
debug-cmd : "npm run debug"
stop-cmd : "npm stop"

chart-path: "chart/ibm-nodejs-sample"
