image:
  __metadata:
    label: "Image"
  repository:
    __metadata:
      name: "Image"
      label: "Image repository"
      description: "Docker image location"
      type: "string"
      immutable: true
      required: true
  tag:
    __metadata:
      name: "tag"
      label: "Image tag"
      description: "Determines the Node.js version this sample is built upon"
      options: 
      - label: "Node.js 8"
        value: "8"
      - label: "Node.js 6"
        value: "6"
  pullPolicy:
    __metadata:
      name: "pullPolicy"
      label: "Image pull policy"
      type: "string"
      immutable: true
      required: true
service:
  __metadata:
    label: "Service configuration"
  name: 
    __metadata:
      name: "Name"
      label: "Service name"
      description: "This is the Kubernetes service name: it must be letters and/or text for this sample"
      type: "string"
      immutable: false
      required: true
      validation: "^[a-zA-Z]([-a-zA-Z0-9])+$"
  type: 
    __metadata:
      name: "Type"
      label: "Service type"
      description: "This is the Kubernetes service type: choose ClusterIP to only have the deployed sample accessible inside of your cluster, or via port forwarding. NodePort should be used if you want anyone who can access this IBM Cloud Private instance to view the application"
      type: "string"
      immutable: false
      required: true
      options:
      - label: "Node Port"
        value: "NodePort"
      - label: "Cluster IP"
        value: "ClusterIP"
  port:
    __metadata:
      name: "Port"
      label: "Port"
      description: "This is the port for the service and must match the Node.js listen server port number and what is exposed in the Dockerfile"
      type: "string"
      immutable: true
      required: true
